#ifndef VERSIONINFO_H
#define VERSIONINFO_H

//#define BUILD_TIMESTAMP "@BUILD_TIMESTAMP@"
//#define CLIENT_VERSION  "@CLIENT_VERSION@"
#define BUILD_TIMESTAMP "Wed Aug 31 11:55:24 EDT 2022"
#define CLIENT_VERSION  "1.3.10"
#endif /* VERSIONINFO_H */
